### ISSUE TITLE
Weird Alignment After Drawer Opens

### ISSUE THREAD

**Issue by mcblum** [cavis/gridheist#1]
For some reason my screen does this when I open an image...
![screen shot 2013-07-31 at 4 08 39 pm](https://f.cloud.github.com/assets/1761867/889781/de52c384-fa25-11e2-9918-c66ff052d950.png)

**Comment by cavis** [comment]
Having trouble reproducing this error on my mac.  So far, I've only seen it in Chrome + Win7, and only on navigation to a new page.  (Refreshing the page never produces the error).  I'll keep digging.

**Comment by cavis** [comment]
Seems it was some sort of issue with the browser/jquery reporting the wrong gallery `$.width()` on the initial load.  Reloads would work out okay.  Solved it in v0.0.4 by wrapping the thumbnails in an inner container, which has an independent width from the base element.  Try it now!  (Make sure you clear your cache, or do a hard refresh).
