### ISSUE TITLE
Preloader Function

### ISSUE THREAD

**Issue by mcblum** [cavis/gridheist#2]
Would be awesome to be able to define load x number of images in front of active image, load x number behind active image.

**Comment by cavis** [comment]
The current `preloadImages` option just loads all of them at once - needs to be smarter!

Note to self: this is preloading the "big/expanded" image, not the thumbnails.  May eventually need to investigate progressively loading thumbnails as you scroll.  But functionality seems okay with ~200 images.

**Comment by cavis** [comment]
Note to self: I need a new public domain image source.  Looks like pixabay keeps expiring my test images!  Argg!!!

**Comment by cavis** [comment]
Implemented!  Demo at http://cav.is/gridheist/test/preloader.html - preloaded thumbs get a blue square on them in the demo.
